### ISSUE TITLE
TcpSequentialClient uses incorrect size of the connectionPool

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stIncMale/pies#9]
```
poolConfig.setMaxTotal MUST be determined with regard to maximum expected 
parallel invocations of the TcpSequentialClient.send method
```

Original issue reported on code.google.com by `Valentin...@gmail.com` on 25 Feb 2015 at 7:11

**Comment by stIncMale** [comment]
Fixed in
https://github.com/stIncMale/pies/commit/d14ea4f37d36abce220ad137f657521fd6d8e6b9
